<?php
/**
 * Language versions: /ms/, /zh-hans/ and /zh-hant/ beside the English site.
 *
 * DESIGN, and why
 * ---------------
 * The English site is live production content and is never modified. It is
 * delivered four different ways at once: page bodies stored in the database
 * (services, case studies, articles), theme template files with the copy
 * hardcoded in them (home, team, contact, header, footer), theme options
 * (hero copy, stats) and HTML generated by PHP. Separate WordPress Pages per
 * language would miss most of that, because the template-driven pages have no
 * stored body to copy. So this is a language LAYER, not a set of copies:
 *
 *   1. URL     /ms/team/ is served by the SAME page as /team/. The prefix is
 *              removed from the request before WordPress parses it, so no
 *              posts, no rewrite rules and no English URL change. Nothing is
 *              written to the database.
 *   2. TEXT    The rendered page is translated from a per-language dictionary
 *              (inc/i18n/<lang>.php), by text node. One mechanism therefore
 *              covers templates, options, menus and stored content alike.
 *              A string with no entry stays English, which is also how an
 *              English edit that outdates a translation fails: visibly, and
 *              never by breaking the page.
 *   3. SEO     Each translated page gets its own title and description
 *              (explicit, not string-matched, because the live ones come from
 *              Rank Math settings), a self-referencing canonical, the right
 *              <html lang>, and hreflang between every language that exists.
 *   4. LINKS   Internal links point to the same language where that page is
 *              translated, and stay on the English URL where it is not.
 *
 * A page "exists" in a language exactly when that language's data file has an
 * SEO entry for it, so adding a page is: add its strings and its SEO entry.
 * Only pages that exist are reachable under a prefix; any other prefixed URL
 * redirects to its English equivalent. A translated URL therefore never shows
 * an English body under a non-English address.
 *
 * No plugin, no core change, no parent-theme change. Loaded from functions.php.
 */

defined( 'ABSPATH' ) || exit;

/**
 * The languages. English has no prefix and keeps its existing URLs.
 *
 * `hreflang` uses language + SCRIPT for Chinese (zh-Hans / zh-Hant), not
 * country codes: the distinction is Simplified against Traditional, not
 * mainland against Taiwan. `og` is Open Graph's own locale vocabulary, which
 * is a separate spec and does use country codes.
 *
 * @return array<string, array<string, string>>
 */
function remotive_i18n_languages() {
	return array(
		'en'      => array( 'prefix' => '',        'hreflang' => 'en',      'html' => '',        'native' => 'English',       'short' => 'EN', 'og' => '' ),
		'ms'      => array( 'prefix' => 'ms',      'hreflang' => 'ms-MY',   'html' => 'ms-MY',   'native' => 'Bahasa Melayu', 'short' => 'BM', 'og' => 'ms_MY' ),
		'zh-hans' => array( 'prefix' => 'zh-hans', 'hreflang' => 'zh-Hans', 'html' => 'zh-Hans', 'native' => '简体中文',       'short' => '简',  'og' => 'zh_CN' ),
		'zh-hant' => array( 'prefix' => 'zh-hant', 'hreflang' => 'zh-Hant', 'html' => 'zh-Hant', 'native' => '繁體中文',       'short' => '繁',  'og' => 'zh_TW' ),
	);
}

/** The language of this request: 'en', 'ms', 'zh-hans' or 'zh-hant'. */
function remotive_i18n_lang() {
	return isset( $GLOBALS['remotive_i18n_lang'] ) ? $GLOBALS['remotive_i18n_lang'] : 'en';
}

/** Path prefix of the site, for a WordPress installed in a subdirectory. */
function remotive_i18n_base() {
	return rtrim( (string) wp_parse_url( get_option( 'home' ), PHP_URL_PATH ), '/' );
}

/**
 * Recognise a language prefix and remove it from the request.
 *
 * Runs while the theme loads, which is before WordPress parses the request, so
 * `WP::parse_request()` resolves the English page and everything downstream
 * (templates, canonical redirect, conditional tags) behaves exactly as it does
 * for the English URL. The original URL is kept for diagnostics.
 *
 * Only front-end page requests are touched. Anything that looks like a
 * WordPress internal (wp-*, feeds, sitemaps, robots, xmlrpc) under a prefix is
 * left alone, so it simply 404s rather than becoming a second way in.
 */
function remotive_i18n_boot() {
	$GLOBALS['remotive_i18n_lang'] = 'en';

	if ( empty( $_SERVER['REQUEST_URI'] ) || 'cli' === PHP_SAPI ) {
		return;
	}

	$uri  = (string) wp_unslash( $_SERVER['REQUEST_URI'] ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput
	$path = (string) wp_parse_url( $uri, PHP_URL_PATH );
	$qs   = wp_parse_url( $uri, PHP_URL_QUERY );
	$base = remotive_i18n_base();
	$rel  = ( '' !== $base && 0 === strpos( $path, $base . '/' ) ) ? substr( $path, strlen( $base ) ) : $path;

	// Earlier builds used /zh-cn/ and /zh-tw/ for the landing pages. The script
	// names (hans, hant) are the stable ones, so the old addresses move there.
	if ( preg_match( '#^/(zh-cn|zh-tw)(/.*)?$#i', $rel, $old ) ) {
		wp_safe_redirect( $base . '/' . ( 'zh-cn' === strtolower( $old[1] ) ? 'zh-hans' : 'zh-hant' ) . ( isset( $old[2] ) ? $old[2] : '/' ) . ( $qs ? '?' . $qs : '' ), 301 );
		exit;
	}

	if ( ! preg_match( '#^/(ms|zh-hans|zh-hant)(/.*)?$#i', $rel, $m ) ) {
		return;
	}

	// /MS/team/ is the same page as /ms/team/ and must not become a second address.
	if ( $m[1] !== strtolower( $m[1] ) ) {
		wp_safe_redirect( $base . '/' . strtolower( $m[1] ) . ( isset( $m[2] ) ? $m[2] : '/' ) . ( $qs ? '?' . $qs : '' ), 301 );
		exit;
	}

	$rest = isset( $m[2] ) ? $m[2] : '';

	if ( preg_match( '#^/(wp-|feed|sitemap|robots|xmlrpc)#', $rest ) ) {
		return;
	}

	// /ms -> /ms/ so a language home has one address.
	if ( '' === $rest ) {
		wp_safe_redirect( $base . '/' . $m[1] . '/' . ( $qs ? '?' . $qs : '' ), 301 );
		exit;
	}

	$GLOBALS['remotive_i18n_lang'] = $m[1];
	$_SERVER['REMOTIVE_I18N_ORIGINAL_URI'] = $uri;
	$_SERVER['REQUEST_URI']                = $base . $rest . ( $qs ? '?' . $qs : '' );

	// WordPress takes the path from PATH_INFO in preference to REQUEST_URI when the
	// server sets it (some Apache, nginx/FastCGI and CLI-server setups do), so the
	// prefix has to come off there too or the page would not resolve.
	foreach ( array( 'PATH_INFO', 'ORIG_PATH_INFO' ) as $var ) {
		if ( ! empty( $_SERVER[ $var ] ) && preg_match( '#^/(?:ms|zh-hans|zh-hant)(/.*)?$#', $_SERVER[ $var ], $pm ) ) {
			$_SERVER[ $var ] = isset( $pm[1] ) && '' !== $pm[1] ? $pm[1] : '/';
		}
	}
}
remotive_i18n_boot();

/* ==========================================================================
 * Dictionary
 * ======================================================================== */

/**
 * Normal form for comparing text: entities decoded, typographic quotes and
 * non-breaking spaces flattened, whitespace collapsed. Applied to BOTH the
 * dictionary keys and the rendered text, so it does not matter that
 * wptexturize turned a straight apostrophe into a curly one on the way out.
 */
function remotive_i18n_norm( $text ) {
	$text = html_entity_decode( (string) $text, ENT_QUOTES | ENT_HTML5, 'UTF-8' );
	$text = str_replace( array( "\u{2019}", "\u{2018}", "\u{201C}", "\u{201D}", "\u{00A0}" ), array( "'", "'", '"', '"', ' ' ), $text );

	return trim( preg_replace( '/\s+/u', ' ', $text ) );
}

/**
 * A language's data file, loaded once and prepared for lookup.
 *
 * `strings`  English => translation. A key may contain %n% (any whole number,
 *            e.g. a year or a count) or %count% (a number WORD such as "Ten",
 *            which the page builds from the live roster size), so a sentence
 *            that quotes a changing number does not silently stop matching.
 * `seo`      English path => [ title, description ]. Its keys are also the
 *            list of pages that exist in this language ('' is the home page).
 * `count_words`  English number word => the language's word for it.
 *
 * @return array{strings:array,patterns:array,seo:array,count_words:array}
 */
function remotive_i18n_data( $lang ) {
	static $cache = array();

	if ( isset( $cache[ $lang ] ) ) {
		return $cache[ $lang ];
	}

	$file = get_theme_file_path( 'inc/i18n/' . $lang . '.php' );
	$raw  = ( 'en' !== $lang && is_readable( $file ) ) ? require $file : array();
	$out  = array( 'strings' => array(), 'patterns' => array(), 'seo' => array(), 'count_words' => array(), 'published' => array() );

	// Shipped translations are the baseline; anything saved in the admin screen
	// (Tools > Translations) is laid on top and wins. Edits live in the database,
	// so a theme update can never overwrite a translator's work.
	$db    = remotive_i18n_overrides( $lang );
	$merge = array();

	foreach ( isset( $raw['strings'] ) ? $raw['strings'] : array() as $source => $target ) {
		$merge[ remotive_i18n_norm( $source ) ] = $target;
	}

	foreach ( $db['strings'] as $source => $target ) {
		$merge[ $source ] = $target;
	}

	foreach ( $merge as $key => $target ) {
		if ( false === strpos( $key, '%n%' ) && false === strpos( $key, '%count%' ) ) {
			$out['strings'][ $key ] = $target;
			continue;
		}

		$regex = preg_quote( $key, '#' );
		$regex = str_replace( array( preg_quote( '%n%', '#' ), preg_quote( '%count%', '#' ) ), array( '(\d[\d,]*)', '([A-Za-z]+|\d[\d,]*)' ), $regex );

		$out['patterns'][] = array( 'regex' => '#^' . $regex . '$#u', 'target' => $target, 'has_count' => false !== strpos( $key, '%count%' ) );
	}

	$out['seo'] = isset( $raw['seo'] ) ? $raw['seo'] : array();

	foreach ( $db['seo'] as $path => $fields ) {
		$out['seo'][ $path ] = array_merge( isset( $out['seo'][ $path ] ) ? $out['seo'][ $path ] : array(), $fields );
	}

	$out['count_words'] = isset( $raw['count_words'] ) ? $raw['count_words'] : array();
	$out['published']   = $db['published'];

	$cache[ $lang ] = $out;

	return $out;
}

/**
 * The pages that have language versions without anyone switching them on.
 *
 * The brief for the site is one simple, clean page that explains what the
 * company does, in English, Malay and Chinese, rather than many pages: so the
 * home page is the only one live in each language. Every other translation in
 * the dictionaries is ready but off; Tools > Translations turns a page on, and
 * a page that is off redirects to its English address. Filterable, for a site
 * that launches with a different single page.
 *
 * @return string[] English paths; '' is the home page.
 */
function remotive_i18n_default_live_pages() {
	return array_map( 'strval', (array) apply_filters( 'remotive_i18n_live_pages', array( '' ) ) );
}

/** Does this page (an English path such as 'team', '' for home) exist in this language? */
function remotive_i18n_available( $lang, $key ) {
	if ( 'en' === $lang ) {
		return true;
	}

	if ( null === $key ) {
		return false;
	}

	$data = remotive_i18n_data( $lang );

	if ( empty( $data['seo'][ $key ]['title'] ) ) {
		return false; // A page with no title and description is not ready to exist.
	}

	// A page is live only if someone switched it on in the admin screen, except
	// the pages the site launches with (see remotive_i18n_default_live_pages()).
	if ( isset( $data['published'][ $key ] ) ) {
		return (bool) $data['published'][ $key ];
	}

	return in_array( $key, remotive_i18n_default_live_pages(), true );
}

/**
 * Translations saved through the admin screen, for one language.
 *
 * Reads nothing and costs nothing until the tables exist, and never throws:
 * a missing table or a database hiccup means "no overrides", and the shipped
 * dictionary carries on, so a translated page can never go down over this.
 *
 * @return array{strings:array,seo:array,published:array}
 */
function remotive_i18n_overrides( $lang ) {
	global $wpdb;
	static $cache = array();

	if ( isset( $cache[ $lang ] ) ) {
		return $cache[ $lang ];
	}

	$out = array( 'strings' => array(), 'seo' => array(), 'published' => array() );

	if ( ! function_exists( 'remotive_i18n_db_ready' ) || ! remotive_i18n_db_ready() ) {
		return $out;
	}

	$suppress = $wpdb->suppress_errors( true );
	$rows     = $wpdb->get_results( $wpdb->prepare( 'SELECT kind, ref, source, target FROM ' . remotive_i18n_table( '' ) . " WHERE lang = %s AND status = 'approved' AND target <> ''", $lang ), ARRAY_A ); // phpcs:ignore WordPress.DB.PreparedSQL
	$pages    = $wpdb->get_results( $wpdb->prepare( 'SELECT path, published FROM ' . remotive_i18n_table( 'pages' ) . ' WHERE lang = %s', $lang ), ARRAY_A ); // phpcs:ignore WordPress.DB.PreparedSQL
	$wpdb->suppress_errors( $suppress );

	foreach ( (array) $rows as $row ) {
		if ( 'string' === $row['kind'] ) {
			$out['strings'][ remotive_i18n_norm( $row['source'] ) ] = $row['target'];
		} elseif ( 'title' === $row['kind'] ) {
			$out['seo'][ $row['ref'] ]['title'] = $row['target'];
		} elseif ( 'desc' === $row['kind'] ) {
			$out['seo'][ $row['ref'] ]['description'] = $row['target'];
		}
	}

	foreach ( (array) $pages as $row ) {
		$out['published'][ $row['path'] ] = (int) $row['published'];
	}

	$cache[ $lang ] = $out;

	return $out;
}

/**
 * Text that is the same in every language: no words (numbers, symbols), an
 * email address, or something the site itself stores as a fact (a person's
 * name or initials, an address line). These are never translated and never
 * reported as missing.
 */
function remotive_i18n_is_invariant( $core ) {
	static $facts = null;

	if ( ! preg_match( '/[A-Za-z]{2,}/', $core ) || false !== strpos( $core, '@' ) ) {
		return true;
	}

	if ( null === $facts ) {
		$facts = array( 'Remotive Media Asia' => true );

		if ( function_exists( 'remotive_team_members' ) ) {
			foreach ( remotive_team_members() as $member ) {
				$facts[ remotive_i18n_norm( $member['name'] ) ] = true;
				$words   = preg_split( '/\s+/', trim( $member['name'] ) );
				$initial = mb_strtoupper( mb_substr( $words[0], 0, 1 ) ) . ( count( $words ) > 1 ? mb_strtoupper( mb_substr( end( $words ), 0, 1 ) ) : '' );
				$facts[ $initial ] = true;
			}
		}

		if ( function_exists( 'remotive_get_theme_option' ) ) {
			foreach ( array( 'address_line_1', 'address_line_2', 'address_line_3', 'legal_name' ) as $option ) {
				$value = remotive_get_theme_option( $option );

				if ( is_string( $value ) && '' !== $value ) {
					$facts[ remotive_i18n_norm( $value ) ] = true;
				}
			}
		}
	}

	return isset( $facts[ $core ] );
}

/**
 * Translate one piece of text. Returns the translation, or null to leave it.
 *
 * @param string $core    Normalised text.
 * @param string $lang    Target language.
 * @param array  $missing Collects text that has no entry (for the admin report).
 */
function remotive_i18n_lookup( $core, $lang, &$missing ) {
	$data = remotive_i18n_data( $lang );

	if ( isset( $data['strings'][ $core ] ) ) {
		return $data['strings'][ $core ];
	}

	foreach ( $data['patterns'] as $pattern ) {
		if ( ! preg_match( $pattern['regex'], $core, $m ) ) {
			continue;
		}

		$value = $m[1];

		if ( $pattern['has_count'] ) {
			$words = $data['count_words'];
			$word  = $value;
			$value = isset( $words[ $word ] ) ? $words[ $word ] : ( isset( $words[ ucfirst( $word ) ] ) ? $words[ ucfirst( $word ) ] : $word );

			// "Ten" starts a sentence and "ten" sits inside one; the translation follows suit
			// (a no-op for Chinese, which has no case).
			if ( $value !== $word && ctype_lower( substr( $word, 0, 1 ) ) ) {
				$value = mb_strtolower( mb_substr( $value, 0, 1 ) ) . mb_substr( $value, 1 );
			}
		}

		return str_replace( array( '%n%', '%count%' ), $value, $pattern['target'] );
	}

	// Punctuation left alone in a text node, between two inline elements, is
	// sentence punctuation and nothing else. Chinese uses its own marks for it.
	if ( 0 === strpos( $lang, 'zh' ) ) {
		$marks = array( '.' => "\u{3002}", ',' => "\u{FF0C}", ';' => "\u{FF1B}", ':' => "\u{FF1A}" );

		if ( isset( $marks[ $core ] ) ) {
			return $marks[ $core ];
		}
	}

	if ( ! remotive_i18n_is_invariant( $core ) ) {
		$missing[ $core ] = true;
	}

	return null;
}

/* ==========================================================================
 * Which page is this, and where does it live in each language
 * ======================================================================== */

/**
 * The current page as an English path ('' for the home page), or null when it
 * is not a single page we can translate (archive, search, 404, feed ...).
 */
function remotive_i18n_key() {
	if ( is_front_page() && ! is_paged() ) {
		return '';
	}

	// The posts page (the blog index) is a page you chose in Settings > Reading,
	// but WordPress treats it as an archive, not a single page.
	if ( is_home() && ! is_paged() && (int) get_option( 'page_for_posts' ) ) {
		$permalink = get_permalink( (int) get_option( 'page_for_posts' ) );
	} elseif ( is_singular() ) {
		$permalink = get_permalink();
	} else {
		return null;
	}

	$path = (string) wp_parse_url( $permalink, PHP_URL_PATH );
	$base = remotive_i18n_base();

	if ( '' !== $base && 0 === strpos( $path, $base ) ) {
		$path = substr( $path, strlen( $base ) );
	}

	return trim( $path, '/' );
}

/** URL of a page in a language. $key '' is that language's home page. */
function remotive_i18n_url( $lang, $key ) {
	$langs  = remotive_i18n_languages();
	$prefix = $langs[ $lang ]['prefix'];
	$path   = ( '' === $prefix ? '' : $prefix . '/' ) . ( '' === $key ? '' : trim( $key, '/' ) . '/' );

	return home_url( '/' . $path );
}

/**
 * Give an internal URL its language prefix, or null to leave it as it is.
 * A link is only prefixed when that page exists in the language; otherwise it
 * stays on the English URL (the fallback), so no link ever lands on a redirect.
 */
function remotive_i18n_localise_url( $url, $lang ) {
	$url  = html_entity_decode( $url, ENT_QUOTES | ENT_HTML5, 'UTF-8' );
	$home = untrailingslashit( home_url() );
	$base = remotive_i18n_base();

	if ( '' === $url || '#' === $url[0] ) {
		return null;
	}

	if ( 0 === strpos( $url, $home . '/' ) || $url === $home ) {
		$url = substr( $url, strlen( $home ) );
		$url = '' === $url ? '/' : $url;
	} elseif ( '/' === $url[0] && ( ! isset( $url[1] ) || '/' !== $url[1] ) ) {
		if ( '' !== $base && 0 === strpos( $url, $base . '/' ) ) {
			$url = substr( $url, strlen( $base ) );
		}
	} else {
		return null; // External, mailto:, tel:, protocol-relative.
	}

	$parts    = wp_parse_url( 'http://x' . $url );
	$path     = isset( $parts['path'] ) ? $parts['path'] : '/';
	$key      = trim( $path, '/' );
	$query    = isset( $parts['query'] ) ? '?' . $parts['query'] : '';
	$fragment = isset( $parts['fragment'] ) ? '#' . $parts['fragment'] : '';

	if ( preg_match( '#^(wp-|feed|sitemap|robots|xmlrpc|ms/|zh-hans/|zh-hant/)#', $key ) || preg_match( '#\.[a-z0-9]{2,5}$#i', $key ) ) {
		return null;
	}

	if ( ! remotive_i18n_available( $lang, $key ) ) {
		return null;
	}

	return remotive_i18n_url( $lang, $key ) . $query . $fragment;
}

/**
 * This page's own English address, query string included. On a translated
 * request the URL was rewritten to exactly this before WordPress saw it, so it
 * is simply what WordPress thinks the current URL is.
 */
function remotive_i18n_english_url() {
	$request = isset( $_SERVER['REQUEST_URI'] ) ? wp_unslash( $_SERVER['REQUEST_URI'] ) : '/'; // phpcs:ignore WordPress.Security.ValidatedSanitizedInput
	$path    = (string) wp_parse_url( $request, PHP_URL_PATH );
	$query   = wp_parse_url( $request, PHP_URL_QUERY );
	$base    = remotive_i18n_base();

	if ( '' !== $base && 0 === strpos( $path, $base ) ) {
		$path = substr( $path, strlen( $base ) );
	}

	return home_url( '' === $path ? '/' : $path ) . ( $query ? '?' . $query : '' );
}

/* ==========================================================================
 * Language selector
 * ======================================================================== */

/**
 * The selector: English, Bahasa Melayu, 简体中文, 繁體中文, as an inline list in the
 * footer's bottom bar. It is deliberately NOT in the header: the header already has
 * no spare room at most widths, and adding a control to it made the nav wrap and the
 * header grow (measured: 85px to 123px at 1100px wide) on the live English site. The
 * footer bar wraps naturally and leaves the English layout above it untouched.
 *
 * Each link goes to
 * the equivalent page where that translation exists, and to that language's
 * home page where it does not, so it can never point at a missing page. The
 * English link is always the current page's own English address, which is what
 * the request was rewritten to.
 */
function remotive_i18n_render_switcher() {
	$langs   = remotive_i18n_languages();
	$current = remotive_i18n_lang();
	$key     = remotive_i18n_key();
	$items   = '';

	foreach ( $langs as $code => $lang ) {
		if ( 'en' === $code ) {
			$href = remotive_i18n_english_url();
		} else {
			$href = remotive_i18n_url( $code, remotive_i18n_available( $code, $key ) ? $key : '' );
		}

		$items .= sprintf(
			'<li><a href="%1$s" lang="%2$s" hreflang="%2$s"%3$s>%4$s</a></li>',
			esc_url( $href ),
			esc_attr( $lang['hreflang'] ),
			$code === $current ? ' aria-current="true"' : '',
			esc_html( $lang['native'] )
		);
	}

	$strings = remotive_i18n_data( $current )['strings'];
	$label   = isset( $strings['Language'] ) ? $strings['Language'] : 'Language';

	return '<nav class="rm-lang" translate="no" aria-label="' . esc_attr( $label ) . '"><ul class="rm-lang__list">' . $items . '</ul></nav>';
}

/* ==========================================================================
 * SEO: hreflang, and the translated page's own head
 * ======================================================================== */

/**
 * hreflang between every language that has this page. Printed on the English
 * page as well as the translations, because each side has to point at the
 * others for the relationship to count. Only pages that have a translation get
 * any; English pages with none are left exactly as they were.
 */
function remotive_i18n_hreflang() {
	if ( ! apply_filters( 'remotive_i18n_translates_request', true ) ) {
		return; // The page prints its own alternates.
	}

	$key = remotive_i18n_key();

	if ( null === $key ) {
		return;
	}

	$alternates = array( 'en' => remotive_i18n_url( 'en', $key ) );

	foreach ( remotive_i18n_languages() as $code => $lang ) {
		if ( 'en' !== $code && remotive_i18n_available( $code, $key ) ) {
			$alternates[ $code ] = remotive_i18n_url( $code, $key );
		}
	}

	if ( count( $alternates ) < 2 ) {
		return;
	}

	$langs = remotive_i18n_languages();

	foreach ( $alternates as $code => $url ) {
		printf( '<link rel="alternate" hreflang="%s" href="%s" />' . "\n", esc_attr( $langs[ $code ]['hreflang'] ), esc_url( $url ) );
	}

	printf( '<link rel="alternate" hreflang="x-default" href="%s" />' . "\n", esc_url( $alternates['en'] ) );
}
add_action( 'wp_head', 'remotive_i18n_hreflang', 1 );

/** Replace a meta tag's content if the tag exists. Returns the new head and whether it was found. */
function remotive_i18n_set_meta( $head, $attr, $name, $content ) {
	$pattern = '#<meta\s+[^>]*' . $attr . '=(["\'])' . preg_quote( $name, '#' ) . '\1[^>]*>#i';

	if ( ! preg_match( $pattern, $head, $m ) ) {
		return array( $head, false );
	}

	$tag = preg_replace( '#\scontent=(["\']).*?\1#is', ' content="' . esc_attr( $content ) . '"', $m[0], 1, $count );

	if ( ! $count ) {
		$tag = rtrim( substr( $m[0], 0, -1 ), '/ ' ) . ' content="' . esc_attr( $content ) . '" />';
	}

	return array( str_replace( $m[0], $tag, $head ), true );
}

/**
 * Make the <head> of a translated page its own: title, description, social
 * tags, a canonical that points at itself (never at the English page) and no
 * shortlink to the English ID. Works whether the canonical comes from core or
 * from Rank Math, because it edits what was actually printed.
 */
function remotive_i18n_filter_head( $head, $lang, $key ) {
	$data  = remotive_i18n_data( $lang );
	$langs = remotive_i18n_languages();
	$seo   = $data['seo'][ $key ];
	$self  = remotive_i18n_url( $lang, $key );

	// Every <title>: Rank Math prints one inside its own block and the theme's title-tag
	// support prints another, and a translated page must not keep an English one.
	$head = preg_replace( '#<title[^>]*>.*?</title>#is', '<title>' . esc_html( $seo['title'] ) . '</title>', $head, -1, $n );

	if ( ! $n ) {
		$head .= '<title>' . esc_html( $seo['title'] ) . '</title>';
	}

	list( $head, $found ) = remotive_i18n_set_meta( $head, 'name', 'description', $seo['description'] );

	if ( ! $found ) {
		$head .= '<meta name="description" content="' . esc_attr( $seo['description'] ) . '" />' . "\n";
	}

	foreach ( array( array( 'property', 'og:title', $seo['title'] ), array( 'property', 'og:description', $seo['description'] ), array( 'name', 'twitter:title', $seo['title'] ), array( 'name', 'twitter:description', $seo['description'] ), array( 'property', 'og:locale', $langs[ $lang ]['og'] ), array( 'property', 'og:url', $self ) ) as $tag ) {
		list( $head ) = remotive_i18n_set_meta( $head, $tag[0], $tag[1], $tag[2] );
	}

	$canonical = '<link rel="canonical" href="' . esc_url( $self ) . '" />';
	$head      = preg_replace( '#<link\s+rel=(["\'])canonical\1[^>]*>#i', $canonical, $head, 1, $n );

	if ( ! $n ) {
		$head .= $canonical . "\n";
	}

	$head = preg_replace( '#<link\s+rel=(["\'])shortlink\1[^>]*>\s*#i', '', $head );

	// The comments-feed link names the English post and points at its English feed.
	$head = preg_replace( '#<link\s+rel=(["\'])alternate\1[^>]*type=(["\'])application/rss\+xml\2[^>]*Comments Feed[^>]*>\s*#i', '', $head );

	return remotive_i18n_filter_schema( $head, $lang, $key );
}

/**
 * Structured data (JSON-LD) for a translated page.
 *
 * A translated page whose JSON-LD still says it is the English URL, in en-US,
 * with the English title, contradicts its own canonical. So the page's OWN
 * nodes (the WebPage-type node and its breadcrumb) become the translated page:
 * its URL, its ids, its title and description, its language, and breadcrumb
 * links that stay in the language. Shared entities (the Organization, the
 * WebSite) are the same company and site in every language and are left as
 * they are, so every language points at one entity. Applied to every JSON-LD
 * block, so it also covers an SEO plugin's own graph for the same page.
 */
function remotive_i18n_filter_schema( $head, $lang, $key ) {
	$seo        = remotive_i18n_data( $lang )['seo'][ $key ];
	$self       = remotive_i18n_url( $lang, $key );
	$english    = remotive_i18n_url( 'en', $key );
	$html       = remotive_i18n_languages()[ $lang ]['html'];
	// Rank Math describes an article page with a WebPage node AND an Article node; both are this page.
	$page_types = array( 'WebPage', 'CollectionPage', 'AboutPage', 'ContactPage', 'ItemPage', 'FAQPage', 'ProfilePage', 'QAPage', 'Article', 'BlogPosting', 'NewsArticle', 'TechArticle' );

	return preg_replace_callback(
		'#(<script\b[^>]*type=(["\'])application/ld\+json\2[^>]*>)(.*?)(</script>)#is',
		function ( $m ) use ( $seo, $self, $english, $html, $page_types, $lang ) {
			$data = json_decode( $m[3], true );

			if ( ! is_array( $data ) ) {
				return $m[0];
			}

			// 1. This page's own node ids, and what each becomes.
			$ids     = array();
			$collect = function ( $node ) use ( &$collect, &$ids, $english, $self, $page_types ) {
				if ( isset( $node['@id'], $node['@type'] ) && is_string( $node['@id'] ) && 0 === strpos( $node['@id'], $english . '#' ) ) {
					if ( array_intersect( (array) $node['@type'], array_merge( $page_types, array( 'BreadcrumbList' ) ) ) ) {
						$ids[ $node['@id'] ] = $self . substr( $node['@id'], strlen( $english ) );
					}
				}

				foreach ( $node as $child ) {
					if ( is_array( $child ) ) {
						$collect( $child );
					}
				}
			};
			$collect( $data );

			// 2. Rewrite.
			$walk = function ( $node ) use ( &$walk, $ids, $seo, $self, $english, $html, $page_types, $lang ) {
				foreach ( $node as $name => $value ) {
					if ( is_string( $value ) && isset( $ids[ $value ] ) ) {
						$node[ $name ] = $ids[ $value ];
					} elseif ( is_array( $value ) ) {
						$node[ $name ] = $walk( $value );
					}
				}

				$types = isset( $node['@type'] ) ? (array) $node['@type'] : array();

				if ( array_intersect( $types, $page_types ) ) {
					if ( isset( $node['url'] ) || array_intersect( $types, array( 'WebPage', 'CollectionPage', 'AboutPage', 'ContactPage', 'ItemPage', 'FAQPage', 'ProfilePage', 'QAPage' ) ) ) {
						$node['url'] = $self;
					}

					$node['inLanguage'] = $html;

					foreach ( array( 'name' => 'title', 'headline' => 'title', 'description' => 'description' ) as $field => $source ) {
						if ( isset( $node[ $field ] ) ) {
							$node[ $field ] = $seo[ $source ];
						}
					}
				}

				if ( in_array( 'BreadcrumbList', $types, true ) && isset( $node['itemListElement'] ) && is_array( $node['itemListElement'] ) ) {
					$last = count( $node['itemListElement'] ) - 1;

					foreach ( $node['itemListElement'] as $i => $item ) {
						if ( isset( $item['item'] ) && is_string( $item['item'] ) ) {
							$current = untrailingslashit( $item['item'] ) === untrailingslashit( $english );
							$local   = $current ? $self : remotive_i18n_localise_url( $item['item'], $lang );

							if ( $local ) {
								$node['itemListElement'][ $i ]['item'] = $local;
							}

							if ( $current && $i === $last ) {
								$node['itemListElement'][ $i ]['name'] = $seo['title'];
							}
						}

						if ( isset( $item['name'] ) && is_string( $item['name'] ) && $i !== $last ) {
							$strings = remotive_i18n_data( $lang )['strings'];
							$key_n   = remotive_i18n_norm( $item['name'] );

							if ( isset( $strings[ $key_n ] ) ) {
								$node['itemListElement'][ $i ]['name'] = $strings[ $key_n ];
							}
						}
					}
				}

				return $node;
			};

			$out = wp_json_encode( $walk( $data ), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_HEX_TAG );

			return false === $out ? $m[0] : $m[1] . $out . $m[4];
		},
		$head
	);
}

/* ==========================================================================
 * Output translation
 * ======================================================================== */

/**
 * Walk a page body and translate it, collecting anything without an entry.
 *
 * This single walk is used both to translate a page and to SCAN one (run
 * against a language with an empty dictionary, so every translatable string
 * lands in $missing). Scanning therefore cannot disagree with translating
 * about what counts as a string.
 *
 * @param string $body    The HTML after </head>.
 * @param string $lang    Target language, or any code with no dictionary to scan.
 * @param array  $missing Receives the normalised text of every string without an entry.
 * @return string The translated body.
 */
function remotive_i18n_translate_body( $body, $lang, &$missing ) {
	$skip_tags = array( 'script', 'style', 'textarea', 'pre', 'code', 'noscript', 'svg', 'template', 'select' );
	$skip_name = null;
	$skip_deep = 0;
	$out       = '';
	$tokens    = preg_split( '#(<!--.*?-->|<![^>]*>|<(?:/?)[a-zA-Z][^\s/>]*(?:"[^"]*"|\'[^\']*\'|[^\'">])*>)#s', $body, -1, PREG_SPLIT_DELIM_CAPTURE );

	// A regex failure (a pathological page, a PCRE limit) must never blank the
	// page: hand back the English HTML as it was.
	if ( false === $tokens ) {
		}

	foreach ( $tokens as $token ) {
		if ( '' === $token ) {
			continue;
		}

		if ( '<' !== $token[0] ) {
			if ( null !== $skip_name ) {
				$out .= $token;
				continue;
			}

			preg_match( '/^(\s*)(.*?)(\s*)$/su', $token, $m );
			$core = remotive_i18n_norm( $m[2] );
			$hit  = '' === $core ? null : remotive_i18n_lookup( $core, $lang, $missing );
			$out .= null === $hit ? $token : $m[1] . esc_html( $hit ) . $m[3];
			continue;
		}

		if ( 0 === strpos( $token, '<!' ) ) {
			$out .= $token;
			continue;
		}

		preg_match( '#^<(/?)([a-zA-Z][^\s/>]*)#', $token, $t );
		$closing = '/' === $t[1];
		$tag     = strtolower( $t[2] );

		if ( null !== $skip_name ) {
			if ( $tag === $skip_name ) {
				$skip_deep += $closing ? -1 : ( '/>' === substr( $token, -2 ) ? 0 : 1 );

				if ( $skip_deep <= 0 ) {
					$skip_name = null;
				}
			}

			$out .= $token;
			continue;
		}

		if ( $closing ) {
			$out .= $token;
			continue;
		}

		if ( in_array( $tag, $skip_tags, true ) || preg_match( '#\s(?:translate=(["\'])no\1|id=(["\'])wpadminbar\2)#i', $token ) ) {
			if ( '/>' !== substr( $token, -2 ) ) {
				$skip_name = $tag;
				$skip_deep = 1;
			}

			$out .= $token;
			continue;
		}

		$out .= remotive_i18n_filter_tag( $token, $tag, $lang, $missing );
	}


	if ( false === $tokens ) {
		return $body;
	}

	return $out;
}

/**
 * FAQ structured data for a translated page.
 *
 * The FAQPage node is built from the English template, so on a translated page
 * its questions and answers would be English beside a translated page. The
 * visible questions and answers are already translated by this point, so they
 * are read back from the finished page and written into the node, which keeps
 * the structured data identical to what the visitor reads. Left alone if the
 * counts do not match, so a page that changed shape is never half-rewritten.
 */
function remotive_i18n_translate_faq_schema( $head, $body ) {
	if ( false === strpos( $head, 'FAQPage' ) || ! preg_match_all( '#<details\b[^>]*>\s*<summary[^>]*>(.*?)</summary>(.*?)</details>#is', $body, $hits, PREG_SET_ORDER ) ) {
		return $head;
	}

	$pairs = array();

	foreach ( $hits as $hit ) {
		$q = trim( html_entity_decode( wp_strip_all_tags( $hit[1] ), ENT_QUOTES | ENT_HTML5, 'UTF-8' ) );
		$a = trim( preg_replace( '/\s+/u', ' ', html_entity_decode( wp_strip_all_tags( $hit[2] ), ENT_QUOTES | ENT_HTML5, 'UTF-8' ) ) );

		if ( '' !== $q && '' !== $a ) {
			$pairs[] = array( $q, $a );
		}
	}

	return preg_replace_callback(
		'#(<script\b[^>]*type=(["\'])application/ld\+json\2[^>]*>)(.*?)(</script>)#is',
		function ( $m ) use ( $pairs ) {
			$data = json_decode( $m[3], true );

			if ( ! is_array( $data ) || false === strpos( $m[3], 'FAQPage' ) ) {
				return $m[0];
			}

			$walk = function ( $node ) use ( &$walk, $pairs ) {
				foreach ( $node as $key => $value ) {
					if ( is_array( $value ) ) {
						$node[ $key ] = $walk( $value );
					}
				}

				if ( isset( $node['@type'], $node['mainEntity'] ) && 'FAQPage' === $node['@type'] && is_array( $node['mainEntity'] ) && count( $node['mainEntity'] ) === count( $pairs ) ) {
					foreach ( array_values( $node['mainEntity'] ) as $i => $entity ) {
						$node['mainEntity'][ $i ]['name']                   = $pairs[ $i ][0];
						$node['mainEntity'][ $i ]['acceptedAnswer']['text'] = $pairs[ $i ][1];
					}
				}

				return $node;
			};

			$out = wp_json_encode( $walk( $data ), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_HEX_TAG );

			return false === $out ? $m[0] : $m[1] . $out . $m[4];
		},
		$head
	);
}

/**
 * Translate a finished page.
 *
 * The HTML is walked tag by tag. Text is translated by text node and a short
 * list of attributes by value; script, style, textarea, code, inline SVG and
 * anything marked translate="no" (or the admin bar) are passed through
 * untouched, as are comments. Attributes are matched with their quotes
 * respected, so a ">" inside a value cannot end a tag early.
 */
function remotive_i18n_filter_output( $html ) {
	$lang = remotive_i18n_lang();

	if ( 'en' === $lang || false === strpos( $html, '</head>' ) ) {
		return $html;
	}

	$key     = isset( $GLOBALS['remotive_i18n_key'] ) ? $GLOBALS['remotive_i18n_key'] : null;
	$langs   = remotive_i18n_languages();
	$missing = array();

	list( $head, $body ) = explode( '</head>', $html, 2 );

	if ( null !== $key && remotive_i18n_available( $lang, $key ) ) {
		$head = remotive_i18n_filter_head( $head, $lang, $key );
	}

	$head = preg_replace( '#(<html\b[^>]*?\slang=)(["\']).*?\2#i', '$1"' . $langs[ $lang ]['html'] . '"', $head, 1 );

	$out = remotive_i18n_translate_body( $body, $lang, $missing );

	$head = remotive_i18n_translate_faq_schema( $head, $out );

	if ( ! empty( $missing ) && isset( $_GET['rm_i18n_missing'] ) && current_user_can( 'manage_options' ) ) { // phpcs:ignore WordPress.Security.NonceVerification
		$out .= "\n<!-- rm_i18n missing (" . count( $missing ) . "):\n" . str_replace( '--', '- -', implode( "\n", array_keys( $missing ) ) ) . "\n-->";
	}

	return $head . '</head>' . $out;
}

/**
 * One opening tag: translate its visible attributes and localise its link.
 */
function remotive_i18n_filter_tag( $token, $tag, $lang, &$missing ) {
	// Attribute text that a person reads or a screen reader announces.
	$token = preg_replace_callback(
		'#(\s(?:aria-label|placeholder|title|alt|data-caption)=)(["\'])(.*?)\2#s',
		function ( $m ) use ( $lang, &$missing, $tag ) {
			if ( 'link' === $tag || 'meta' === $tag ) {
				return $m[0];
			}

			$core = remotive_i18n_norm( $m[3] );
			$hit  = '' === $core ? null : remotive_i18n_lookup( $core, $lang, $missing );

			return null === $hit ? $m[0] : $m[1] . $m[2] . esc_attr( $hit ) . $m[2];
		},
		$token
	);

	if ( 'input' === $tag ) {
		$token = preg_replace_callback(
			'#(\svalue=)(["\'])(.*?)\2#s',
			function ( $m ) use ( $token, $lang, &$missing ) {
				if ( ! preg_match( '#\stype=(["\'])(?:submit|button)\1#i', $token ) ) {
					return $m[0];
				}

				$hit = remotive_i18n_lookup( remotive_i18n_norm( $m[3] ), $lang, $missing );

				return null === $hit ? $m[0] : $m[1] . $m[2] . esc_attr( $hit ) . $m[2];
			},
			$token
		);
	}

	if ( 'a' === $tag ) {
		$token = preg_replace_callback(
			'#(\shref=)(["\'])(.*?)\2#s',
			function ( $m ) use ( $lang ) {
				$local = remotive_i18n_localise_url( $m[3], $lang );

				return null === $local ? $m[0] : $m[1] . $m[2] . esc_url( $local ) . $m[2];
			},
			$token
		);
	}

	// The colour-mode button's label is rewritten by script on every click, so
	// it has to be told the translated words or it would flip back to English.
	if ( 'button' === $tag && false !== strpos( $token, 'id="rmThemeToggle"' ) ) {
		$data  = remotive_i18n_data( $lang );
		$light = isset( $data['strings']['Light'] ) ? $data['strings']['Light'] : 'Light';
		$dark  = isset( $data['strings']['Dark'] ) ? $data['strings']['Dark'] : 'Dark';
		$token = str_replace( 'id="rmThemeToggle"', 'id="rmThemeToggle" data-label-light="' . esc_attr( $light ) . '" data-label-dark="' . esc_attr( $dark ) . '"', $token );
	}

	return $token;
}

/**
 * WordPress redirects to its own canonical form of an address: it adds a
 * missing trailing slash, resolves ?p=ID, drops index.php. It computes that
 * from the English page, so left alone it would turn /ms/team into /team/ and
 * drop the visitor out of their language. The redirect gets its prefix back
 * whenever the target page exists in the language, and otherwise goes to the
 * English page, as every other untranslated address does.
 */
function remotive_i18n_canonical_redirect( $redirect_url ) {
	$lang = remotive_i18n_lang();

	if ( 'en' === $lang || ! is_string( $redirect_url ) ) {
		return $redirect_url;
	}

	$local = remotive_i18n_localise_url( $redirect_url, $lang );

	return $local ? $local : $redirect_url;
}
add_filter( 'redirect_canonical', 'remotive_i18n_canonical_redirect' );

/**
 * Start translating a language request, or send it to its English address if
 * that page has no translation. Never redirects a genuine 404, so a mistyped
 * address still reports itself as missing.
 */
function remotive_i18n_start() {
	$lang = remotive_i18n_lang();

	if ( 'en' === $lang ) {
		return;
	}

	// Pages that carry their own copy for every language (the ad landing pages)
	// opt out here, so they are neither translated nor redirected to English.
	if ( ! apply_filters( 'remotive_i18n_translates_request', true ) ) {
		return;
	}

	$key = remotive_i18n_key();

	if ( is_404() ) {
		$key = null;
	} elseif ( ! remotive_i18n_available( $lang, $key ) ) {
		wp_safe_redirect( remotive_i18n_english_url(), 302 );
		exit;
	}

	$GLOBALS['remotive_i18n_key'] = $key;

	if ( ! headers_sent() ) {
		header( 'Content-Language: ' . remotive_i18n_languages()[ $lang ]['html'] );
	}

	ob_start( 'remotive_i18n_filter_output' );
}
add_action( 'template_redirect', 'remotive_i18n_start', 0 );

/* ==========================================================================
 * Sitemap
 * ======================================================================== */

/**
 * Every translated URL, with its language alternates, as an XML sitemap.
 *
 * Kept separate from the existing sitemap on purpose: Rank Math owns that one
 * and it must not change. This one is advertised in robots.txt, which is how
 * a crawler finds it independently of any SEO plugin, and is offered to Rank
 * Math's sitemap index as well when that plugin exposes the hook.
 */
function remotive_i18n_sitemap_xml() {
	$langs = remotive_i18n_languages();
	$pages = array();

	foreach ( $langs as $code => $lang ) {
		if ( 'en' === $code ) {
			continue;
		}

		foreach ( array_keys( remotive_i18n_data( $code )['seo'] ) as $key ) {
			$pages[ $key ] = true;
		}
	}

	$xml = '<?xml version="1.0" encoding="UTF-8"?>' . "\n" . '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">' . "\n";

	foreach ( array_keys( $pages ) as $key ) {
		$alternates = array( 'en' => remotive_i18n_url( 'en', $key ) );

		foreach ( $langs as $code => $lang ) {
			if ( 'en' !== $code && remotive_i18n_available( $code, $key ) ) {
				$alternates[ $code ] = remotive_i18n_url( $code, $key );
			}
		}

		$post    = '' === $key ? get_post( (int) get_option( 'page_on_front' ) ) : get_page_by_path( $key );
		$lastmod = $post ? gmdate( 'c', strtotime( $post->post_modified_gmt . ' UTC' ) ) : '';

		foreach ( $alternates as $code => $url ) {
			if ( 'en' === $code ) {
				continue; // English is already in the existing sitemap.
			}

			$xml .= '<url><loc>' . esc_url( $url ) . '</loc>' . ( $lastmod ? '<lastmod>' . $lastmod . '</lastmod>' : '' );

			foreach ( $alternates as $alt_code => $alt_url ) {
				$xml .= '<xhtml:link rel="alternate" hreflang="' . esc_attr( $langs[ $alt_code ]['hreflang'] ) . '" href="' . esc_url( $alt_url ) . '"/>';
			}

			$xml .= '<xhtml:link rel="alternate" hreflang="x-default" href="' . esc_url( $alternates['en'] ) . '"/></url>' . "\n";
		}
	}

	return $xml . '</urlset>';
}

/** Serve /sitemap-languages.xml. */
function remotive_i18n_serve_sitemap( $wp ) {
	if ( 'sitemap-languages.xml' !== $wp->request ) {
		return;
	}

	status_header( 200 );
	header( 'Content-Type: application/xml; charset=UTF-8' );
	header( 'X-Robots-Tag: noindex, follow' ); // A sitemap file is not itself a page to index.
	echo remotive_i18n_sitemap_xml(); // phpcs:ignore WordPress.Security.EscapeOutput
	exit;
}
add_action( 'parse_request', 'remotive_i18n_serve_sitemap' );

/** Tell crawlers about it, without touching whatever else robots.txt says. */
function remotive_i18n_robots( $output ) {
	return rtrim( $output ) . "\n\nSitemap: " . home_url( '/sitemap-languages.xml' ) . "\n";
}
add_filter( 'robots_txt', 'remotive_i18n_robots', 99 );

/**
 * Offer it to Rank Math's sitemap index too. Best effort: if that filter does
 * not exist in the installed version this never runs, and robots.txt (above)
 * plus a Search Console submission are what make it discoverable.
 */
function remotive_i18n_rankmath_index( $xml ) {
	return $xml . '<sitemap><loc>' . esc_url( home_url( '/sitemap-languages.xml' ) ) . '</loc></sitemap>';
}
add_filter( 'rank_math/sitemap/index', 'remotive_i18n_rankmath_index' );
